"""
Deploys the gradient-boosted-tree open-ended abstention classifier found
in calibrate_abstention_v2_signals.py (Attempt B): 0.644 -> 0.737 mean CV
accuracy over the identical 4 deployed signals (query_confidence,
query_top1_score, question_match_any, bm25_vector_agreement), just a
different classifier (GradientBoostingClassifier, max_depth=3,
n_estimators=50, deliberately shallow given n=371) instead of logistic
regression.

Verified robust before deploying, not just measured once:
  - 5-seed x 5-fold CV (same protocol as every other abstention
    experiment): 0.7374 mean, beats the deployed 4-signal logistic
    regression in every seed, both paired t-test and Wilcoxon p<0.0001
    (both tests agree -- this project's standing bar for treating a
    result as more than suggestive).
  - Stable across 5 different classifier random_states (0.7374-0.7390,
    not a lucky-seed artifact).
  - In-sample (full-data) accuracy 0.873 vs. 0.737 CV -- a normal,
    moderate train/generalization gap for a shallow tree ensemble, not
    the near-100%-in-sample/near-chance-CV pattern that would indicate
    memorization.

Deployment choice: serialize via joblib (self-generated by this script,
from this project's own data -- NOT a third-party pickle downloaded from
the internet, a materially different trust profile than the externally
-hosted pickle checkpoints declined elsewhere this session for security
reasons). sklearn is already a project dependency (used throughout the
calibration scripts); this is the first time a fitted sklearn model
artifact is loaded at PRODUCTION inference time rather than only during
offline calibration, a deliberate, considered step given how strongly
this result held up under scrutiny.

Usage: python scripts/calibrate_abstention_gbt_final.py
"""

import json
import sys
from pathlib import Path

import joblib
import numpy as np
from sklearn.ensemble import GradientBoostingClassifier

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from pipeline.hybrid_retriever import HybridRetriever
from scripts.calibrate_abstention_newsignals import compute_new_signals
from scripts.calibrate_abstention import load_rows, build_synthetic_entity_calibration_set

OUT_MODEL_PATH = ROOT / "results" / "abstention_gbt_open_ended.joblib"
OUT_META_PATH = ROOT / "results" / "abstention_gbt_open_ended_metadata.json"
FEATURES = ["query_confidence", "query_top1_score", "question_match_any", "bm25_vector_agreement"]
RANDOM_STATE = 0


def main():
    out_of_scope, answerable_sample = load_rows()
    synthetic_queries, synthetic_labels = build_synthetic_entity_calibration_set()
    retriever = HybridRetriever()
    queries = out_of_scope + answerable_sample + synthetic_queries
    labels = [True] * len(out_of_scope) + [False] * len(answerable_sample) + synthetic_labels

    data = {"labels": [], "query_confidence": [], "query_top1_score": [],
            "question_match_any": [], "bm25_vector_agreement": []}
    for q, label in zip(queries, labels):
        results, meta = retriever.retrieve_adaptive(q)
        if meta["route"] != "open_ended":
            continue
        if results:
            qc = results[0]["query_confidence"]
            qt = results[0]["query_top1_score"]
        else:
            qc, qt = 0.0, 0.0
        qma, bva = compute_new_signals(retriever, q, results)
        data["labels"].append(label)
        data["query_confidence"].append(qc)
        data["query_top1_score"].append(qt)
        data["question_match_any"].append(qma)
        data["bm25_vector_agreement"].append(bva)

    n = len(data["labels"])
    labels_arr = np.array(data["labels"], dtype=int)
    X = np.column_stack([np.array(data[f]) for f in FEATURES])

    clf = GradientBoostingClassifier(max_depth=3, n_estimators=50, random_state=RANDOM_STATE)
    clf.fit(X, labels_arr)
    in_sample_acc = float(clf.score(X, labels_arr))

    OUT_MODEL_PATH.parent.mkdir(parents=True, exist_ok=True)
    joblib.dump(clf, OUT_MODEL_PATH)

    metadata = {
        "n": n,
        "features": FEATURES,
        "model": "GradientBoostingClassifier",
        "max_depth": 3,
        "n_estimators": 50,
        "random_state": RANDOM_STATE,
        "in_sample_accuracy": round(in_sample_acc, 4),
        "cv_mean_accuracy_5seed_5fold": 0.7374,
        "cv_std_accuracy": 0.0445,
        "vs_deployed_4signal_logreg_paired_ttest_p": 0.0000,
        "vs_deployed_4signal_logreg_paired_wilcoxon_p": 0.0000,
        "stability_across_classifier_random_states": [0.7379, 0.7374, 0.7390, 0.7374, 0.7374],
        "source_script": "scripts/calibrate_abstention_v2_signals.py + scripts/calibrate_abstention_gbt_final.py",
    }
    with open(OUT_META_PATH, "w", encoding="utf-8") as f:
        json.dump(metadata, f, indent=2)

    print(f"n={n}, in-sample accuracy={in_sample_acc:.4f}")
    print(f"Wrote {OUT_MODEL_PATH}")
    print(f"Wrote {OUT_META_PATH}")


if __name__ == "__main__":
    main()
